spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #thymeleaf配置
  thymeleaf:
    #关闭缓存
    cache: false
    servlet:
      content-type: text/html
    # 模板编码
    encoding: UTF-8
    prefix: /templates/
    suffix: .html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/room_booking?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    hikari:
      #连接池名（据说是最快的连接池）
      pool-name: DataHikariCP
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 18000
      #最大连接数，默认10
      maximum-pool-size: 10
      #从连接池返回的连接自动提交
      auto-commit: true
      #连接最大存活时间，0表示永久存活，默认1800000（30分钟）
      max-lifetime: 1800000
      #连接超时时间，默认30000（30秒）
      connection-timeout: 30000
      #测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  main:
    # 允许循环依赖
    allow-circular-references: true

#Mybatis-plus配置
mybatis-plus:
  #配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置Mybatis数据返回数据别名（默认别名是类名）
  type-aliases-package: com.mp.demo.data.entity
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true #自动驼峰转换

logging:
  level:
    com.mp.demo.mapper: debug

server:
  max-http-header-size: 40960
  port: 8080

pagehelper:
  reasonable: true
  support-methods-arguments: true
#  offset-as-page-num: true
#  row-bounds-with-count: true
  helper-dialect: mysql
#  params: count=countSql

#开启接口文档
knife4j:
  enable: true
